version: "3.12"
services:
  app:
    build: .
    volumes:
      - .:/home/OtelApp
    ports:
      - 8000:8000
    image: app:django
    container_name: OtelApp
    command: python manage.py runserver 0.0.0.0:8000