# Generated by Django 4.2.3 on 2023-10-09 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtelYonetim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Otel Adı')),
                ('image', models.ImageField(upload_to='Logo', verbose_name='Otel Logosu')),
                ('address', models.CharField(max_length=150, verbose_name='Otel Adresi')),
                ('badcount', models.IntegerField(verbose_name='Otel Yatak Sayısı')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Otel Sahibi')),
            ],
        ),
        migrations.CreateModel(
            name='OtelOda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.IntegerField(verbose_name='Oda Numarası')),
                ('roomtype', models.CharField(max_length=50, verbose_name='Oda Tipi')),
                ('roombadcount', models.IntegerField(verbose_name='Oda Yatak Sayısı')),
                ('roomprice', models.IntegerField(verbose_name='Odanın Fiyatı')),
                ('roomactive', models.BooleanField(default=True, verbose_name='Oda Aktif Mi?')),
                ('roomproblemreason', models.TextField(blank=True, verbose_name='Odanın Problemi Nedir?')),
                ('otel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtelApp.otelyonetim', verbose_name='Otelin Adı')),
            ],
        ),
        migrations.CreateModel(
            name='KonukBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Konaklayan Adı')),
                ('last_name', models.CharField(max_length=50, verbose_name='Konaklayan Soyadı')),
                ('nationality', models.CharField(max_length=50, verbose_name='Konuk Uyruğu')),
                ('guest_tc', models.CharField(max_length=11, verbose_name='Konuk Tc Numarası')),
                ('guest_id', models.CharField(blank=True, max_length=50, verbose_name='Konaklayan Passaport ID')),
                ('checkin_date', models.DateField(verbose_name='Giriş Tarihi')),
                ('checkout_date', models.DateField(blank=True, verbose_name='Çıkış Tarihi')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtelApp.oteloda', verbose_name='Oda Tipi')),
            ],
        ),
    ]
