# Generated by Django 4.2.3 on 2023-10-09 18:59

import OtelApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konukbilgileri',
            name='guest_tr_id',
            field=models.IntegerField(validators=[OtelApp.models.integer_length], verbose_name='Konaklayan Tc Kimlik Numarası'),
        ),
    ]
