# Generated by Django 4.2.3 on 2023-10-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0002_alter_konukbilgileri_guest_tr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konukbilgileri',
            name='checkout_date',
            field=models.DateField(blank=True, verbose_name='Çıkış Tarihi'),
        ),
        migrations.AlterField(
            model_name='otelyonetim',
            name='image',
            field=models.ImageField(upload_to='Logo', verbose_name='Otel Logosu'),
        ),
    ]
