# Generated by Django 4.2.3 on 2023-10-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0002_alter_oteloda_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konukbilgileri',
            name='guest_tc',
            field=models.CharField(default='11 karakterlidir', max_length=11, verbose_name='Konuk Tc Numarası'),
        ),
    ]
