# Generated by Django 4.2.3 on 2023-10-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0003_alter_konukbilgileri_guest_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='oteloda',
            name='roomclean',
            field=models.BooleanField(default=True, verbose_name='Oda Temiz Mi?'),
        ),
        migrations.AddField(
            model_name='oteloda',
            name='roomdefective',
            field=models.BooleanField(default=False, verbose_name='Oda Arızalı Mı?'),
        ),
    ]
