# Generated by Django 4.2.3 on 2023-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0003_alter_konukbilgileri_checkout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konukbilgileri',
            name='guest_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Konaklayan Passaport ID'),
        ),
        migrations.AlterField(
            model_name='otelyonetim',
            name='badcount',
            field=models.IntegerField(verbose_name='Otel Yatak Sayısı'),
        ),
    ]
