# Generated by Django 4.2.3 on 2023-10-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0004_oteloda_roomclean_oteloda_roomdefective'),
    ]

    operations = [
        migrations.AddField(
            model_name='oteloda',
            name='roomisempty',
            field=models.BooleanField(default=1, verbose_name='Oda Dolu Mu?'),
            preserve_default=False,
        ),
    ]
