# Generated by Django 4.2.3 on 2023-10-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0007_oteloda_roomimage_alter_oteloda_roomisempty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oteloda',
            name='roomimage',
        ),
    ]
