# Generated by Django 4.2.3 on 2023-10-15 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0009_alter_oteloda_roomactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oteloda',
            name='roombadcount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Oda Yatak Sayısı'),
        ),
    ]
