# Generated by Django 4.2.3 on 2023-10-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0012_alter_oteloda_roomisempty'),
    ]

    operations = [
        migrations.AddField(
            model_name='konukbilgileri',
            name='guest_note',
            field=models.TextField(blank=True, verbose_name='Müşteri İçin Not'),
        ),
        migrations.AlterField(
            model_name='konukbilgileri',
            name='guest_tc',
            field=models.CharField(max_length=11, verbose_name='Konuk Tc Numarası'),
        ),
    ]
