# Generated by Django 4.2.3 on 2023-10-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0013_konukbilgileri_guest_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konukbilgileri',
            name='guest_tc',
            field=models.CharField(blank=True, max_length=11, verbose_name='Konuk Tc Numarası'),
        ),
        migrations.AlterField(
            model_name='oteloda',
            name='roomprice',
            field=models.IntegerField(blank=True, verbose_name='Odanın Fiyatı'),
        ),
    ]
