# Generated by Django 4.2.6 on 2023-10-20 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0015_alter_oteloda_roomprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='konukbilgileri',
            name='otel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OtelApp.otelyonetim', verbose_name='Otel'),
            preserve_default=False,
        ),
    ]
