# Generated by Django 4.2.6 on 2023-10-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0016_konukbilgileri_otel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='Giriş Tarihi')),
                ('checkout_date', models.DateField(verbose_name='Çıkış Tarihi')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtelApp.konukbilgileri', verbose_name='Konaklayan')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtelApp.oteloda', verbose_name='Oda')),
            ],
            options={
                'unique_together': {('room', 'checkin_date', 'checkout_date')},
            },
        ),
    ]
