# Generated by Django 4.2.6 on 2023-10-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelApp', '0017_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='oteloda',
            name='roomreserved',
            field=models.BooleanField(default=False, verbose_name='Oda Rezerve Edildi Mi?'),
        ),
    ]
